### PR TITLE
Do not create API client for offline commands

### LINKED ISSUE #94: version command not working
**Environment (required):**
- OS: macOS  (Darwin)
- Version: latest as of now

**Describe the bug**
upctl version does not print the software version, see screenshot below.

**To Reproduce**
1. Download the upctl binary
2. Run command "upctl version"

**Expected behavior**
The version is printed into the terminal.

**Observed behavior**
I get an error about missing user credentials and a generic help text.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by kangasta**
This allows running offline commands, such as upctl version, without having to define credentials.

Fixes #94

### CODE REVIEW

File: internal/commands/command.go [hunk 1]
```diff
@@ -95,6 +100,11 @@ func BuildCommand(child Command, parent *cobra.Command, config *config.Config) C
 
 	// Set run
 	child.Cobra().RunE = func(cmd *cobra.Command, args []string) error {
+		// Do not create service for offline commands, e.g. upctl version
+		if i, ok := child.(OfflineCommand); ok && i.IsOffline() {
```
Comment (kangasta) [inline internal/commands/command.go:104]: Would there be a better way to tell `BuildCommand()` that some commands do not need services connection than this interface check?

Comment (moitias) [reply internal/commands/command.go:104]: This seems fine to me, it's not a completely foreign pattern and other options would need much more changes (lazy init of service? move the service init to `commandRunE` and make it a separate type of a command? something else?).

Although, commonly this pattern has only a member method with no return value (eg `type OfflineCommand interface { IsOffline() }`) as this prevents the confusing situation where something fulfills `OnlineCommand` but the method returns false. That is, using the fulfillment of the interface as the definition rather than what that particular method returns. If you go that route, maybe a good idea to make the name of the method a bit more explicit too - just `IsOffline` doesn't really say much unless one knows the context.

Comment (kangasta) [reply internal/commands/command.go]: I removed the return value and renamed `IsOffline` to `DoesNotUseServices`.

I also though of separate type of command, but that seemed like a lot of work as we probably wont have much commands that don't need the API.

Comment (moitias) [reply internal/commands/command.go]: That works great :+1:

**Review by moitias — APPROVED** [review]
One more small nit that you can choose to ignore if you prefer (sorry for not spotting it earlier) but otherwise looks great to me :+1:

File: internal/commands/root/version.go [hunk 2]
```diff
@@ -17,10 +17,13 @@ type VersionCommand struct {
...
-			{Title: "Version", Key: "version", Value: config.Version},
+			{Title: "Version:", Key: "version", Value: config.Version},
 			{Title: "Build date:", Key: "build_date", Value: config.BuildDate},
 			{Title: "Built with:", Key: "built_with", Value: runtime.Version()},
 		},
 		}},
 	}, nil
 }
+
+// Implement OfflineCommand to tell BuildCommand that this command does not use services
```
[the remark this answers is not in the document]
Comment (kangasta) [reply internal/commands/root/version.go]: Done
